- name: Add repository
  apt_repository:
    repo: universe
    state: present

- name: apt Update
  apt: 
    update_cache: yes

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
